### PR TITLE
Overhaul project

### PR DESCRIPTION
**Pull request by jiekang**
* Simplified source tree, moving all sources under the top level project rather than sub project `server`. No changes to sources
* Updated quarkus and graalvm requirements. Updated integration test with new annotation as a result
* Reworked pom to maintain buildability using README.md instruction set
* Reworked Dockerfile setup to build an image via podman

### CODE REVIEW

**Comment by andrewazores** [comment]
In the Dockerfile.native there is `EXPOSE 8080`, but in the pom I see a default webPort of `8181`. Should these match?

**Comment by andrewazores** [comment]
I checked out this branch, downloaded Graal and set my `GRAALVM_HOME` and tried a `mvn clean verify`:

```
$ mvn clean verify
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< com.redhat.jfr.datasource:jfr-datasource >--------------
[INFO] Building JFR Prototype Datasource 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jfr-datasource ---
[INFO] Deleting /home/andrew/workspace/jfr-datasource/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jfr-datasource ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jfr-datasource ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/andrew/workspace/jfr-datasource/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jfr-datasource ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ jfr-datasource ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/andrew/workspace/jfr-datasource/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ jfr-datasource ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.redhat.jfr.tests.DatasourceTest
2020-06-03 15:42:17,199 INFO  [io.quarkus] (main) Quarkus 1.4.2.Final started in 1.680s. Listening on: http://0.0.0.0:8081
2020-06-03 15:42:17,200 INFO  [io.quarkus] (main) Profile test activated. 
2020-06-03 15:42:17,200 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, vertx, vertx-web]
[ERROR] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0, Time elapsed: 3.605 s <<< FAILURE! - in com.redhat.jfr.tests.DatasourceTest
[ERROR] testGet  Time elapsed: 0.186 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

[ERROR] testPostQueryTimeseries  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testPostSet  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testGetList  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testGetListEmpty  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testPostUpload  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testPostQueryTable  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testGetSearch  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

[ERROR] testPostLoad  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.common.RestAssuredURLManager

2020-06-03 15:42:17,469 INFO  [io.quarkus] (main) Quarkus stopped in 0.053s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DatasourceTest.testGet » NoClassDefFound javax/xml/bind/JAXBException
[ERROR]   DatasourceTest.testGetList » NoClassDefFound Could not initialize class io.qua...
[ERROR]   DatasourceTest.testGetListEmpty » NoClassDefFound Could not initialize class i...
[ERROR]   DatasourceTest.testGetSearch » NoClassDefFound Could not initialize class io.q...
[ERROR]   DatasourceTest.testPostLoad » NoClassDefFound Could not initialize class io.qu...
[ERROR]   DatasourceTest.testPostQueryTable » NoClassDefFound Could not initialize class...
[ERROR]   DatasourceTest.testPostQueryTimeseries » NoClassDefFound Could not initialize ...
[ERROR]   DatasourceTest.testPostSet » NoClassDefFound Could not initialize class io.qua...
[ERROR]   DatasourceTest.testPostUpload » NoClassDefFound Could not initialize class io....
[INFO] 
[ERROR] Tests run: 9, Failures: 0, Errors: 9, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.815 s
[INFO] Finished at: 2020-06-03T15:42:17-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project jfr-datasource: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/andrew/workspace/jfr-datasource/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I get more or less the same looking error output when I try with `-Pnative` or `-Dquarkus.native.container-runtime=podman`, too.

**Comment by andrewazores** [comment]
Huh. On `master` I also have a similar build problem:

```
$ mvn clean verify
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] JFR Prototype Datasource                                           [pom]
[INFO] JMC Prototype Server                                               [jar]
[INFO] 
[INFO] --------------< com.redhat.jfr.datasource:jfr-datasource >--------------
[INFO] Building JFR Prototype Datasource 1.0.0-SNAPSHOT                   [1/2]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jfr-datasource ---
[INFO] 
[INFO] ------------------< com.redhat.jfr.datasource:server >------------------
[INFO] Building JMC Prototype Server 1.0.0-SNAPSHOT                       [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ server ---
[INFO] Deleting /home/andrew/workspace/jfr-datasource/server/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/andrew/workspace/jfr-datasource/server/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/andrew/workspace/jfr-datasource/server/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ server ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/andrew/workspace/jfr-datasource/server/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ server ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.redhat.jfr.tests.DatasourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 s <<< FAILURE! - in com.redhat.jfr.tests.DatasourceTest
[ERROR] com.redhat.jfr.tests.DatasourceTest  Time elapsed: 0.008 s  <<< ERROR!
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   DatasourceTest » NoClassDefFound javax/xml/bind/JAXBException
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JFR Prototype Datasource 1.0.0-SNAPSHOT ............ SUCCESS [  0.106 s]
[INFO] JMC Prototype Server 1.0.0-SNAPSHOT ................ FAILURE [  5.421 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.961 s
[INFO] Finished at: 2020-06-03T16:42:04-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project server: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/andrew/workspace/jfr-datasource/server/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :server
```

Hmm.

```
$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode, sharing)
```

If I search for "noclassdeffound JAXBException" I find things like this:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

So I guess I need to try again with my system JDK set to JDK8. I'll try that and report back.

**Comment by jiekang** [comment]
@andrewazores ah... okay I didn't try it with jdk 11. Yes I can reproduce on 11 and not on 8. Huh, the samples and whatnot for quarkus didn't note that afaict. I'll see if there's support for 11, otherwise will mark in README that 8 as JDK is required :(

**Comment by jiekang** [comment]
@andrewazores okay, I added this jaxb dep, and I think it allowed me to build with 11. I removed the properties you mentioned around 8181, sorry those were leftovers from my attempt to use a quarkus extension for jib, or the jib maven plugin. I'll get back to that in a different PR if I can get it to work. At the moment the expectation is to manually build via the Dockerfile

**Comment by andrewazores** [comment]
Cool, `mvn clean verify` works now. `mvn -Pnative clean verify` does not:

```
$ mvn -Pnative clean verify
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< com.redhat.jfr.datasource:jfr-datasource >--------------
[INFO] Building JFR Prototype Datasource 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jfr-datasource ---
[INFO] Deleting /home/andrew/workspace/jfr-datasource/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jfr-datasource ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ jfr-datasource ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 6 source files to /home/andrew/workspace/jfr-datasource/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ jfr-datasource ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ jfr-datasource ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/andrew/workspace/jfr-datasource/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ jfr-datasource ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.redhat.jfr.tests.DatasourceTest
2020-06-03 17:12:29,673 INFO  [io.quarkus] (main) Quarkus 1.4.2.Final started in 1.680s. Listening on: http://0.0.0.0:8081
2020-06-03 17:12:29,675 INFO  [io.quarkus] (main) Profile test activated. 
2020-06-03 17:12:29,675 INFO  [io.quarkus] (main) Installed features: [cdi, mutiny, vertx, vertx-web]
2020-06-03 17:12:31,175 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-0) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,177 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-0) Loading file: /home/andrew/workspace/jfr-datasource/file-uploads/jmc.cpu.jfr
2020-06-03 17:12:31,589 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-1) {"requestId":"Q107","timezone":"","panelId":2,"dashboardId":null,"range":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z","raw":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z"}},"interval":"100ms","intervalMs":100,"targets":[{"target":"jdk.CPULoad.machineTotal","refId":"A","type":"timeserie"}],"maxDataPoints":958,"scopedVars":{"__interval":{"text":"100ms","value":"100ms"},"__interval_ms":{"text":"100","value":100}},"startTime":1572624866492,"rangeRaw":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z"},"adhocFilters":[]}
2020-06-03 17:12:31,682 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-6) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,697 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-5) Loading file: /home/andrew/workspace/jfr-datasource/file-uploads/jmc.cpu.jfr
2020-06-03 17:12:31,817 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-3) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,897 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-2) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,925 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-0) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,925 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-0) Loading file: /home/andrew/workspace/jfr-datasource/file-uploads/jmc.cpu.jfr
2020-06-03 17:12:31,958 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-1) {"requestId":"Q107","timezone":"","panelId":2,"dashboardId":null,"range":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z","raw":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z"}},"interval":"100ms","intervalMs":100,"targets":[{"target":"jdk.CPULoad.machineTotal","refId":"A","type":"table"}],"maxDataPoints":958,"scopedVars":{"__interval":{"text":"100ms","value":"100ms"},"__interval_ms":{"text":"100","value":100}},"startTime":1572624866492,"rangeRaw":{"from":"2019-11-01T16:07:41.503Z","to":"2019-11-01T16:09:15.171Z"},"adhocFilters":[]}
2020-06-03 17:12:31,996 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-6) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:31,996 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-6) Loading file: /home/andrew/workspace/jfr-datasource/file-uploads/jmc.cpu.jfr
2020-06-03 17:12:32,053 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-3) Uploaded: jmc.cpu.jfr
2020-06-03 17:12:32,053 INFO  [com.red.jfr.eve.RecordingService] (vert.x-eventloop-thread-3) Loading file: /home/andrew/workspace/jfr-datasource/file-uploads/jmc.cpu.jfr
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.946 s - in com.redhat.jfr.tests.DatasourceTest
2020-06-03 17:12:32,148 INFO  [io.quarkus] (main) Quarkus stopped in 0.077s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ jfr-datasource ---
[INFO] Building jar: /home/andrew/workspace/jfr-datasource/target/jfr-datasource-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- quarkus-maven-plugin:1.4.2.Final:build (default) @ jfr-datasource ---
[INFO] [org.jboss.threads] JBoss Threads version 3.1.1.Final
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /home/andrew/workspace/jfr-datasource/target/jfr-datasource-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1367ms
[INFO] 
[INFO] --- quarkus-maven-plugin:1.4.2.Final:native-image (default) @ jfr-datasource ---
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /home/andrew/workspace/jfr-datasource/target/jfr-datasource-1.0.0-SNAPSHOT-native-image-source-jar/jfr-datasource-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /home/andrew/workspace/jfr-datasource/target/jfr-datasource-1.0.0-SNAPSHOT-native-image-source-jar/jfr-datasource-1.0.0-SNAPSHOT-runner.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.929 s
[INFO] Finished at: 2020-06-03T17:12:36-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.4.2.Final:native-image (default) on project jfr-datasource: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Cannot find the `native-image` in the GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image`
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.getNativeImageExecutable(NativeImageBuildStep.java:414)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:158)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:931)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I do have `GRAALVM_HOME` set:
```
$ env | grep GRAAL
GRAALVM_HOME=/home/andrew/graalvm-ce-java11-20.1.0
```

I suppose I also should install the `native-image-installable` from the Graal releases page linked in the README and drop that somewhere in my `PATH`, right? That seems to be what the error message is indicating.

**Comment by jiekang** [comment]
@andrewazores ah.. weird thought new releases had it automatically installed, looks like it's the other way around. I've updated the README again

**Comment by jiekang** [comment]
Oh and the fix to build native images is to run:
```
/path/to/graal-install/bin/gu install native-image
```

**Comment by andrewazores** [comment]
Cool, everything seems to work after I do that.

**Comment by jiekang** [comment]
Thanks for the review, sorry for all the troubles D:

**Pull request merged**
